name: Generate Documentation

on:
  push:
    branches: [ main, documentation ]
    paths-ignore:
        - '.github/**'
        - '.site/**'
        - '.docs/**'
        - '.pio/**'
        - '.vscode/**'
        - 'include/**'

jobs:
  build-documentation:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Doxygen
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz

    - name: Setup Doxygen Awesome
      run: |
        git clone https://github.com/jothepro/doxygen-awesome-css.git
        
        # Create custom header with dark mode toggle
        cat > header.html << 'EOL'
        <!-- HTML header for doxygen -->
        <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
        <html xmlns="http://www.w3.org/1999/xhtml">
        <head>
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=11"/>
        <meta name="generator" content="Doxygen $doxygenversion"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <title>$projectname: $title</title>
        <!-- Darkmode toggle -->
        <script type="text/javascript" src="$relpath^doxygen-awesome-darkmode-toggle.js"></script>
        <script type="text/javascript">
            DoxygenAwesomeDarkModeToggle.init()
        </script>
        </head>
        <body>
        EOL
        
        mv header.html doxygen-awesome-css/
        
    - name: Generate Documentation
      run: doxygen Doxyfile

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/html
        force_orphan: true
        commit_message: 'docs: update documentation'